### ISSUE TITLE
Create object for devCodeCamp in code_schools.yaml

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode_backend#205]
devCodeCamp is a partner and ought to be on our code schools page

They are:

1. VA-approved
2. located at   313 North Plankinton Ave, Milwaukee, WI 53203
3. website:  http://devcodecamp.com/
4.  hardware not included

**Comment by jeremysb1** [comment]
logo is here

https://github.com/OperationCode/operationcode_frontend/issues/751

**Comment by hpjaj** [comment]
@kylemh @jeremysb1 - Heads up, now that https://github.com/OperationCode/operationcode_backend/pull/176 is merged, all `CodeSchool` additions and updates will be done through the database.

There are [API endpoints](https://operationcodeapi.docs.apiary.io/#reference/0/codeschool-|-create/create-a-codeschool-member) to create and update a `CodeSchool` record.  

Next we'll need to complete [this issue](https://github.com/OperationCode/operationcode_backend/issues/185) around CRUD actions on the associated `Location` model.

In the meantime, in order to add/update a Code School, we'll just need the [normal information](https://github.com/OperationCode/operationcode_backend/blob/master/config/code_schools.yml#L22-L35) you have been providing in the `code_schools.yml` file, and we'll just make the update it in prod's db, in realtime.

**Comment by jeremysb1** [comment]
@hpjaj so what do you need from me?

**Comment by PrimeTimeTran** [comment]
@jeremysb1 I submitted a [PR here](https://github.com/OperationCode/operationcode_backend/pull/212) to add them. I put `has_online` false because I'm uncertain as to this. Please confirm if they do or don't have an online component.

**Comment by hpjaj** [comment]
As we have transitioned into managing Code Schools through the database, we will no longer be using that `rake` task, nor the `code_schools.yml` file, to make any Code School updates or additions.

For the time being, until the `Location` endpoints are live, In order to add/update a Code School, we'll just need the [normal information](https://github.com/OperationCode/operationcode_backend/blob/master/config/code_schools.yml#L22-L35) that has been provided in the `code_schools.yml` file, and we'll just make the update it in prod's db, in realtime.  

For example, you can just add a comment to this issue like this (except with devCodeCamps info):

```
name: Wyncode Academy
url: http://wyncode.co
logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/master/src/images/codeSchoolLogos/wyncode.jpg
full_time: true
hardware_included: false
has_online: false
online_only: false
email: weare@wyncode.co
locations:
  - va_accepted: true
    address1: 549 NW 28th Street
    city: Miami
    state: FL
    zip: 33127
```
