### ISSUE TITLE
Add Momentum Learning to code schools

### ISSUE THREAD

**Issue by cndreisbach** [OperationCode/operationcode_backend#260]
# Feature
## Why is this feature being added?

Momentum Learning is a code school in Durham, NC that wishes to be added.

Here is the data for the school:

```
name: Momentum Learning
url: http://www.momentumlearn.com/
logo: https://raw.githubusercontent.com/OperationCode/operationcode_frontend/master/src/images/codeSchoolLogos/momentum.jpg (currently in pull request on operationcode_frontend)
full_time: true
hardware_included: false
has_online: false
online_only: false
email: info@momentumlearn.com
locations:
  - va_accepted: false
    address1: 334 Blackwell St, Suite B001
    city: Durham
    state: NC
    zip: 27701
```
