### ISSUE TITLE
Add V School to Code Schools

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode_backend#298]
# Feature
## Why is this feature being added?
This school has just been approved to accept the GI Bill,  so they're trying to help get the word out. Originally requested in front-end repo: https://github.com/OperationCode/operationcode_frontend/issues/938

## What should your feature do?
Add V School as a code school to production DB.

Prerequisites (~Marking as blocked until these are met~):
- [x] Generate logo from source 
    - requirements: white or transparent background, 200px by 200px, 15px margin on all edges, and less than 0.4MB
- [x] Upload logo to S3 Bucket
- [x] Add logo URL to info below for back-end team

School info:
```
name: V School
url: http://vschool.io/contact/
logo: https://s3.amazonaws.com/operationcode-assets/codeSchoolLogos/v_school.jpg
full_time: true
hardware_included: false
has_online: true
online_only: false
email: team@vschool.io

locations:

- va_accepted: true
  address1: 150 State St.
  address2: # 1
  city: Salt Lake City
  state: UT
  zip: 84111
```
